apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-scheduler
  labels:
    app: banking-scheduler
    keel.sh/policy: force
    keel.sh/trigger: poll
  annotations:
    keel.sh/pollSchedule: "@every 10s"
spec:
  selector:
    matchLabels:
      app: banking-scheduler
  template:
    metadata:
      labels:
        app: banking-scheduler
    spec:
      imagePullSecrets:
        - name: registrypullsecret
      containers:
        - name: scheduler
          imagePullPolicy: Always
          image: docker.pkg.github.com/oryono/scheduler/scheduler:latest
          envFrom:
            - secretRef:
                name: environment-variables