on: push
name: CI
jobs:
  Publish:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
    steps:
      -   uses: actions/checkout@v1
          with:
            fetch-depth: 1

      -   name: build-push
          uses: docker/build-push-action@v1
          with:
            username: "oryono"
            password: ${{ secrets.TOKEN }}
            repository: oryono/banking/banking
            dockerfile: Dockerfile
            registry: docker.pkg.github.com
            tags: latest


  deploy:
    name: deploy to cluster
    needs: Publish
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
    steps:
      -   uses: actions/checkout@master
      -   name: Save DigitalOcean kubeconfig
          uses: digitalocean/action-doctl@master
          env:
            DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
          with:
            args: kubernetes cluster kubeconfig show k8s-1-17-5-do-0-lon1-1591093018670 > $GITHUB_WORKSPACE/.kubeconfig
      -   name: Deploy to DigitalOcean Kubernetes
          run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig apply -f $GITHUB_WORKSPACE/k8s.yml

      -   name: verify deployment
          run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig rollout status deployment/banking-app
